/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jose.ranieri (https://sketchfab.com/jose.ranieri)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/adult-dragon-b1667e01947148e5bea733b3b69cdccc
Title: Adult Dragon
*/

import * as THREE from 'three'
import {useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
// @ts-ignore
import scene from "../../assets/low_poly_dragon.glb"

type GLTFResult = GLTF & {
    nodes: {
        Cube_0: THREE.SkinnedMesh
        Ossos_rootJoint: THREE.Bone
    }
    materials: {
        Material: THREE.MeshBasicMaterial
    }
}


export function DragonForContact({
                                     animationSpeed = 1,
                                     ...props
                                 }: JSX.IntrinsicElements['group'] & {
    animationSpeed?: number
}) {
    const currentAnimation = 'cyclewalk'
    const group = useRef<THREE.Group>(null)
    const { nodes, materials, animations } = useGLTF(scene) as GLTFResult
    const { actions } = useAnimations(animations, group)

    useEffect(() => {
        if (!actions) return

        Object.values(actions).forEach((action) => {
            action?.stop?.()
        })

        const action = actions[currentAnimation as keyof typeof actions]
        if (action) {
            action.setEffectiveTimeScale(animationSpeed)
            action.play()
        }
    }, [actions, currentAnimation, animationSpeed])
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.258}>
                    <group name="Root">
                        <group
                            name="Lamp"
                            position={[15.333, 12.533, 17.243]}
                            rotation={[-0.268, 0.602, 1.932]}
                            scale={2.644}>
                            <group name="Lamp_1" />
                        </group>
                        <group
                            name="Lamp001"
                            position={[-15.333, 12.533, 17.243]}
                            rotation={[-0.268, 0.602, 1.932]}
                            scale={2.644}>
                            <group name="Lamp001_1" />
                        </group>
                        <group
                            name="Lamp002"
                            position={[-15.333, -12.342, 17.243]}
                            rotation={[-0.268, 0.602, 1.932]}
                            scale={2.644}>
                            <group name="Lamp002_1" />
                        </group>
                        <group
                            name="Lamp003"
                            position={[15.333, -12.342, 17.243]}
                            rotation={[-0.268, 0.602, 1.932]}
                            scale={2.644}>
                            <group name="Lamp003_1" />
                        </group>
                        <group
                            name="Lamp004"
                            position={[15.333, -12.342, -12.763]}
                            rotation={[-0.268, 0.602, 1.932]}
                            scale={2.644}>
                            <group name="Lamp004_1" />
                        </group>
                        <group
                            name="Lamp005"
                            position={[-15.333, -12.342, -12.763]}
                            rotation={[-0.268, 0.602, 1.932]}
                            scale={2.644}>
                            <group name="Lamp005_1" />
                        </group>
                        <group
                            name="Lamp006"
                            position={[-15.333, 12.533, -12.763]}
                            rotation={[-0.268, 0.602, 1.932]}
                            scale={2.644}>
                            <group name="Lamp006_1" />
                        </group>
                        <group
                            name="Lamp007"
                            position={[15.333, 12.533, -12.763]}
                            rotation={[-0.268, 0.602, 1.932]}
                            scale={2.644}>
                            <group name="Lamp007_1" />
                        </group>
                        <group name="Ossos" position={[0, 0.041, -0.015]}>
                            <primitive object={nodes.Ossos_rootJoint} />
                            <skinnedMesh
                                name="Cube_0"
                                geometry={nodes.Cube_0.geometry}
                                material={materials.Material}
                                skeleton={nodes.Cube_0.skeleton}
                            />
                            <group name="Cube" position={[0, -0.063, 1.194]} scale={0.507} />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

